PRN221_Asm02/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRN221_Asm02.Models;

namespace PRN221_Asm02.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly PRN221_ASM02Context _context;

        public ProductsController(PRN221_ASM02Context context)
        {
            _context = context;
        }

        // GET: Admin/Products
        public async Task<IActionResult> Index()
        {
            var pRN221_ASM02Context = _context.Products.Include(p => p.Category).Include(p => p.Suppiler);
            return View(await pRN221_ASM02Context.ToListAsync());
        }

        // GET: Admin/Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Suppiler)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName");
            ViewData["SuppilerId"] = new SelectList(_context.Suppliers, "SupplierId", "Address");
            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,SuppilerId,CategoryId,QuantityPerUnit,UnitPrice,ProductImage")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["SuppilerId"] = new SelectList(_context.Suppliers, "SupplierId", "Address", product.SuppilerId);
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["SuppilerId"] = new SelectList(_context.Suppliers, "SupplierId", "Address", product.SuppilerId);
            return View(product);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,SuppilerId,CategoryId,QuantityPerUnit,UnitPrice,ProductImage")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "CategoryName", product.CategoryId);
            ViewData["SuppilerId"] = new SelectList(_context.Suppliers, "SupplierId", "Address", product.SuppilerId);
            return View(product);
        }

        // GET: Admin/Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.Suppiler)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

PRN221_Asm02/Areas/Admin/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRN221_Asm02.Models;

namespace PRN221_Asm02.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StatisticController : Controller
    {
        private readonly PRN221_ASM02Context _context;

        public StatisticController(PRN221_ASM02Context context)
        {
            _context = context;
        }

        // GET: Statistic
        public ActionResult Index()
        {
            return View();
        }

        // GET: Statistic/Details/5
        public async Task<IActionResult> ThongKe(DateTime startDate, DateTime endDate)
        {
            string startDate1 = startDate.ToString();
            string endDate1 = endDate.ToString();
            var orders = await _context.Orders.ToListAsync();
            HttpContext.Session.SetString("StartDate", startDate1);
            HttpContext.Session.SetString("EndDate", endDate1);

            return View(orders);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Orders
                .Include(b => b.Customer)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (bill == null)
            {
                return NotFound();
            }

            var chitietbill = _context.OrderDetails
              .AsNoTracking()
              .Where(x => x.OrderId == bill.OrderId)
              .OrderBy(x => x.OrderId).ToList();
            ViewBag.ChiTiet = chitietbill;

            return View(bill);
        }
    }
}

PRN221_Asm02/Controllers/AccountsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PRN221_Asm02.Models;

namespace PRN221_Asm02.Controllers
{
    [Route("account")]
    public class AccountsController : Controller
    {
        private readonly PRN221_ASM02Context _context;

        public AccountsController(PRN221_ASM02Context context)
        {
            _context = context;
        }

        // GET: Accounts
        
        public ActionResult Index()
        {
            return View();
        }

        [Route("login")]
        [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            var account = await _context.Accounts
                .FirstOrDefaultAsync(a => a.UserName == username && a.Password == password);
            if (username != null && password != null && account != null)
            {
                if (username == "admin" && password == "admin")
                {
                    HttpContext.Session.SetInt32("id", account.AccountId);
                    HttpContext.Session.SetString("username", username);
                    return RedirectToAction("Index", "Admin");
                }
                else
                {
                    HttpContext.Session.SetInt32("id", account.AccountId);
                    HttpContext.Session.SetString("username", username);
                    return RedirectToAction("Index", "Home");
                }    
            }
            else
            {
                ViewBag.error = "Wrong user or password!";
                return View("Index");
            }
        }


        [Route("logout")]
        [HttpGet]
        public IActionResult Logout()
        {
            if (HttpContext.Session.GetString("username") == "admin"){
                HttpContext.Session.Remove("username");
                return RedirectToAction("Index", "Home");
            } else
            {
                HttpContext.Session.Remove("username");
                return RedirectToAction("Index", "Home");
            }
            
        }
        // GET: Accounts/Details/5


        // GET: Accounts/Create
        [HttpGet("[action]")]
        public ActionResult SignUp()
        {
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AccountId,UserName,Password,FullName,Type")] Account account)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    var account1 = await _context.Accounts
                .FirstOrDefaultAsync(a => a.UserName == account.UserName && a.Password == account.Password);
                    if (account1 != null)
                    {
                        ViewBag.Message1 = "Sign Up fail! Username Exist";
                        return View("SignUp");
                    }
                    else
                    {
                        _context.Add(account);
                        await _context.SaveChangesAsync();
                    }
                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(account);
            }
            return View(account);
        }

        [HttpGet("[action]")]
        public ActionResult Contact()
        {
            return View();
        }
    }
}

PRN221_Asm02/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRN221_Asm02.Models;

namespace PRN221_Asm02.Controllers
{
    public class OrdersController : Controller
    {
        private readonly PRN221_ASM02Context _context;

        public OrdersController(PRN221_ASM02Context context)
        {
            _context = context;
        }

        // GET: Bills
        public async Task<IActionResult> Index()
        {

            var PRN221_ASM02Context = _context.Orders.Include(b => b.CustomerId);
            return View(await PRN221_ASM02Context.ToListAsync());
        }

        // GET: Bills/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Orders
                .Include(b => b.CustomerId)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (bill == null)
            {
                return NotFound();
            }

            var chitietbill = _context.OrderDetails
              .AsNoTracking()
              .Where(x => x.OrderId == bill.OrderId)
              .OrderBy(x => x.OrderId).ToList();
            ViewBag.ChiTiet = chitietbill;

            return View(bill);
        }
    }
}

PRN221_Asm02/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PIZZA GOOD</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="/CustomerAssert/images/420.jpg">

    <!-- page css -->
    <link href="~/adminassets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet">

    <!-- Core css -->
    <link href="~/adminassets/css/app.min.css" rel="stylesheet">
    <link rel="stylesheet"
          href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" />
   

</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a href="index.html">
                        <img src="/CustomerAssert/images/420.jpg" alt="Logo" width="103">
                        <img class="logo-fold" src="/CustomerAssert\images\420.jpg" alt="Logo" width="80">
                    </a>
                </div>

                <div class="nav-wrap">
                    <ul class="nav-left">
                        <li class="desktop-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>
                        <li class="mobile-toggle">
                            <a href="javascript:void(0);">
                                <i class="anticon"></i>
                            </a>
                        </li>

                    </ul>
                    <ul class="nav-right">


                        <li class="dropdown dropdown-animated scale-left" style="font-size: 24px; color: lightcoral;">
                                @*Welcome @Context.Session.GetString("username")*@
                            </li>
                            <li>
                                <a asp-controller="Accounts" asp-action="logout" style="text-decoration:none">Logout</a>
                            </li>
                        
                    </ul>
                </div>
            </div>
            <!-- Header END -->
            <!-- Side Nav START -->
            @await Html.PartialAsync("_SideNavPartialView.cshtml")
            <!-- Side Nav END -->
            <!-- Page Container START -->
            <div class="page-container">

                <!-- Content Wrapper START -->
                <div class="main-content">
                    @RenderBody()
                </div>
                <!-- Content Wrapper END -->
                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0">Copyright © 2019 Theme_Nate. All rights reserved.</p>
                        <span>
                            <a href="" class="text-gray m-r-15">Term &amp; Conditions</a>
                            <a href="" class="text-gray">Privacy &amp; Policy</a>
                        </span>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->


        </div>
    </div>


    <!-- Core Vendors JS -->

    <script src="~/adminassets/js/vendors.min.js"></script>
    <!-- page js -->
    <script src="~/adminassetsvendors/chartjs/Chart.min.js"></script>
    <script src="~/adminassetsjs/pages/dashboard-e-commerce.js"></script>

    <!-- Core JS -->

    <script src="~/adminassets/js/app.min.js"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script type="text/javascript"
            src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>



    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   @* @await RenderSectionAsync("Scripts", required: false)*@
</body>

</html>

PRN221_Asm02/Areas/Admin/Views/Shared/_SideNavPartialView.cshtml
<div class="side-nav">
    <div class="side-nav-inner">
        <ul class="side-nav-menu scrollable">
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-build"></i>
                    </span>
                    <span class="title">Manager Product</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a asp-area="Admin" asp-controller="Products" asp-action="Index">Manager Products</a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Categories" asp-action="Index">Manager Category</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-hdd"></i>
                    </span>
                    <span class="title">Manager User</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    
                    <li>
                        <a asp-area="Admin" asp-controller="Accounts" asp-action="Index">Manager User</a>
                    </li>
                  
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-hdd"></i>
                    </span>
                    <span class="title">Manager Order</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">

                    <li>
                        <a asp-area="Admin" asp-controller="Orders" asp-action="Index">Manager Order</a>
                    </li>

                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-form"></i>
                    </span>
                    <span class="title">Statistical</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a asp-area="Admin" asp-controller="Statistic" asp-action="Index">Statistical Income</a>
                    </li>
                </ul>
            </li>
            
            
        </ul>
    </div>
</div>